### ISSUE TITLE
config.js "Developer" args aren't applied

### ISSUE THREAD

**Issue by ItemME** [ElectronForConstruct/construct-devtool#1]
(Not sure if it's the right place but)

`  developer: {
    show_dev_tools: false,
    autoReload: false,
    autoClose: false,
  },
`

Even if we disable everything, it's not applied once builded, the dev tools are still displayed no matter what.

**Comment by Armaldio** [comment]
OK, cleaned the names to be more explicit: 

```js
{
	developer: {
	    showChromeDevTools: true,
	    showConstructDevTools: true,
	    autoReload: true,
	    autoClose: true,
	},
}
```

**Comment by Armaldio** [comment]
Available on branch `develop` (config.js > project > branch)

**Comment by ItemME** [comment]
Issue still there for me.
(For the ConstructDevTools still showing even in the develop branch, but also for Greenworks, compiling somehow with the rest of the sources, even with the arg to exclude them)

Linked you everything needed in PM on Discord.
